name: CI
on:
  push:
    branches:
      - windows
  pull_request:
jobs:
  unix:
    name: Compile
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [8]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - shell: bash
        run: |
          export JABBA=/home/runner/bin/jabba
          $JABBA install graalvm@20.1.0
          export GRAALVM_HOME=$($JABBA which --home graalvm@20.1.0)
          $GRAALVM_HOME/bin/gu install native-image
          export NATIVE_IMAGE_COMMAND=$GRAALVM_HOME/bin/native-image
          csbt test plugin/scripted
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
      - run: java -version
      - run: choco install visualstudio2017-workload-vctools
      - shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          csbt test
